Merge script main kd
openhwgroup/cv32e40x-dv pull request #16
Opened 2023-08-03 14:29 UTC by silabs-krdosvik

Merge from cv32e40s to cv32e40x-dv.
This is related to the PR: ... in core-v-verif
Formal compiles and ci_check:
![image](https://github.com/openhwgroup/cv32e40x-dv/assets/110398284/fd1c0f4e-971a-4cbe-9384-268923a9a995)

2023-08-08 11:31 UTC, silabs-robin commented on regress/cv32e40s_full.yaml
I am a slightly worried about how git can auto-detect with `-X find-renames` in the future, since this 40s file is already checked in as a file that is separate from the 40x equivalent file. Will they forever be disconnected and require a manual fix for each future merge?

I have an idea for how to re-do this whole merge without having to re-resolve every single conflict that occurred.
If we first fix this on this branch now, then all the file content should be correct.
If we then re-do the merge, then we can just copy-paste all the files, and then we end up with both 1) file content being correct, and 2) the git history should be more resilient (wrt. "-X find-renames").

I'm not sure if we _have_ to do that, but if we don't find any reason to believe that the git history is safe as it is now then I think it would be less work to fix it now than to forever live with the alternative.
Maybe it is possible to do some very small experiment to check if it is a real problem? Like, after a fix-up commit, trying a local experiment of changing that particular file and merge only that over to see if "find-renames" still works?

2023-08-08 13:39 UTC, silabs-robin requested changes

2023-08-08 14:54 UTC, silabs-krdosvik commented on tb/uvmt/uvmt_cv32e40x_tb.sv
> -                             .NUM_MHPMCOUNTERS     (CORE_PARAM_NUM_MHPMCOUNTERS),
Good catch! (I think I was consistent here, but when checking the user manual the mhpmcounter is there

2023-08-08 15:01 UTC, silabs-krdosvik commented on tb/uvmt/uvmt_cv32e40x_tb.sv
> -                             .NUM_MHPMCOUNTERS     (CORE_PARAM_NUM_MHPMCOUNTERS),
But now I remember why I removed it:
It is also removed on S even though S also has mhpmcounters, so I assume this is handled somewhere else in the code or no longer needed

2023-08-08 15:08 UTC, silabs-krdosvik commented on tb/uvmt/uvmt_cv32e40x_tb.sv
> -                             .NUM_MHPMCOUNTERS     (CORE_PARAM_NUM_MHPMCOUNTERS),
Whops, on S the mhpmcounters are hardwired to 0, which is not the case on X (thanks @silabs-robin ). Will fix it :-)

2023-08-08 15:09 UTC, silabs-krdosvik commented on tests/cfg/dummy_instr.yaml
Yess! Will delete it.

2023-08-08 15:19 UTC, silabs-krdosvik commented on regress/cv32e40s_full.yaml
Yess. The --find-rename detects how similar each delte/add pair is, and creates renames based on that (https://git-scm.com/docs/git-diff). For now it seems okay to just manually correct the files and delete the s versions.

2023-08-08 15:21 UTC, silabs-robin commented on regress/cv32e40s_full.yaml
> For now it seems okay to just manually correct the files and delete the s versions.

Agreed.

2023-08-08 15:25 UTC, silabs-robin commented on bsp/crt0.S
> To see what is excluded in this merge:
> https://github.com/silabs-krdosvik/cv32e40x-dv/compare/merge_script_main_kd..silabs-krdosvik:cv32e40x-dv:cv32e40x?expand=1

The diff of excluded changes looks good to, IMO.
I can't see anything there that hasn't already been addressed by other comments.

2023-08-09 07:11 UTC, silabs-robin commented on tb/uvmt/uvmt_cv32e40x_tb.sv
> -                             .NUM_MHPMCOUNTERS     (CORE_PARAM_NUM_MHPMCOUNTERS),
Looks good now.

2023-08-09 07:12 UTC, silabs-robin commented on tests/cfg/dummy_instr.yaml
Looks good now.

2023-08-09 07:12 UTC, silabs-robin commented on regress/cv32e40s_full.yaml
Looks good now.

2023-08-09 07:13 UTC, silabs-robin commented on tests/uvmt/base-tests/uvmt_cv32e40s_base_test_constants.sv
Looks good now.

2023-08-09 07:15 UTC, silabs-robin approved these changes
Approving based on:
All feedback resolved.
Commit log looks as expected (old commits, one merge commit, plus minor fixups is ok).
The "exclusion diff" looks good too.

2023-08-09 08:39 UTC, merged