Merge cv32e40s 2023.08.15 10.59
openhwgroup/cv32e40x-dv pull request #20
Opened 2023-08-15 11:14 UTC by silabs-robin

2023-08-15 13:24 UTC, silabs-mateilga commented
Per offline discussion it's hard to determine how thorough we should be in these reviews of already-reviewed PRs, and the diff becomes rather hard to review, as it's 15 changes in one. I've looked over the Rejection diff, and all those decisions seems reasonable.

As we don't have an agreed upon level-of-thoroughness for these reviews, I'm approving this based on a look trough the rejection diff and trust in the approved PRs that are merged.

2023-08-15 13:24 UTC, silabs-mateilga approved these changes

2023-08-15 14:25 UTC, MikeOpenHWGroup requested changes
L(mostly)GTM @silabs-robin.  I am not in a position to review some of the detailed technical aspects of the PR, so I will leave the final approval and merging to other members of the SiLabs team.

I do have one comment about the use of `$urandom()`.

2023-08-15 14:25 UTC, MikeOpenHWGroup commented on env/uvme/vseq/uvme_cv32e40x_wu_wfe_noise_vseq.sv
> +  randcase
I've never been a fan of this coding construct.  Using `$urandom()` means that the delay cannot be precisely constrained and (in some simulators at least) the using the same seed across two simulations yields different results.

2023-08-15 14:36 UTC, silabs-robin commented on env/uvme/vseq/uvme_cv32e40x_wu_wfe_noise_vseq.sv
> +  randcase
The `$urandom()` got introduced in this PR: https://github.com/openhwgroup/core-v-verif/pull/2097

I suspect it mimicked the style of [uvme_cv32e40s_interrupt_noise_vseq](https://github.com/openhwgroup/core-v-verif/blob/cv32e40s/dev/cv32e40s/env/uvme/vseq/uvme_cv32e40s_interrupt_noise_vseq.sv), which has existed since [the 40p's uvme_cv32e40p_interrupt_noise_vseq](https://github.com/openhwgroup/core-v-verif/blob/master/cv32e40p/env/uvme/vseq/uvme_cv32e40p_interrupt_noise_vseq.sv).

2023-08-15 15:00 UTC, MikeOpenHWGroup commented on env/uvme/vseq/uvme_cv32e40x_wu_wfe_noise_vseq.sv
> +  randcase
Correct on both counts.  I would dearly love to remove that from the interrupt virtual sequences as well (however, it "works", so its not really a priority).  The fact that we have this in our code base does not make it a good idea and should not be a reason to add more of it.

2023-08-16 08:08 UTC, silabs-robin commented on env/uvme/vseq/uvme_cv32e40x_wu_wfe_noise_vseq.sv
> +  randcase
> The fact that we have this in our code base does not make it a good idea and should not be a reason to add more of it.

Agreed.

Besides that, this PR is a merge from S to X, so I don't think it is the appropriate place to introduce changes in the wfe_wu sequence.
It should be fixed on the S and then brought over to the X on the next merge.
And, we need to get the X up to date because other things are pending on it.

2023-08-16 09:04 UTC, silabs-hfegran commented on env/uvme/vseq/uvme_cv32e40x_wu_wfe_noise_vseq.sv
> +  randcase
Thanks for the feedback @MikeOpenHWGroup, 

> I've never been a fan of this coding construct. Using `$urandom()` means that the delay cannot be precisely constrained 

This part I agree with, there are room for improvements here - if we need very specific constraints this will not work

> and (in some simulators at least) the using the same seed across two simulations yields different results.

If this is a problem, it should be an LRM violation as it is clearly stated that `randcase` draws its random selection value from `$urandom_range` which exhibits random and thread stability. As both the randcase and the repeat-randomization draws their value from the same stable random-construct, there should be no issue repeating the same test, with the same simulator and top-level seed. 

Let's continue this discussion during our meeting

2023-08-16 09:06 UTC, silabs-hfegran approved these changes

2023-08-16 21:13 UTC, MikeOpenHWGroup commented on env/uvme/vseq/uvme_cv32e40x_wu_wfe_noise_vseq.sv
> +  randcase
@silabs-hfegran is correct, clause 18.14 of the LRM (1800-2017) does indeed state that `$urandom()` and it's ilk do not break random stability.  I stand corrected and will remove my objection to this merge.

2023-08-16 21:13 UTC, MikeOpenHWGroup approved these changes

2023-08-17 06:29 UTC, merged

2023-08-17 11:28 UTC, silabs-robin commented on tb/uvmt/uvmt_cv32e40x_interrupt_assert.sv
> -  property p_wfi_assert_core_sleep_o;
https://github.com/openhwgroup/core-v-verif/pull/2097/files#diff-6577a4a85f81658856f01986b48c167d3a7e0fef34bcd1dd97c906d37946cd7e

2023-08-17 11:29 UTC, silabs-robin commented on tb/uvmt/uvmt_cv32e40x_interrupt_assert.sv
> -  property p_wfi_assert_core_sleep_o;
There was a rewrite of this module. I think I just took the whole change verbatim from the S.

2023-08-17 11:31 UTC, silabs-robin commented on tb/uvmt/uvmt_cv32e40x_interrupt_assert.sv
> +    model_sleepmode === core_sleep_o
I always forget how it works. It is about the difference of comparisons like `1 == X`. If the result of the comparison itself can be X or not, etc.

That too came from this PR https://github.com/openhwgroup/core-v-verif/pull/2097/files#diff-6577a4a85f81658856f01986b48c167d3a7e0fef34bcd1dd97c906d37946cd7e

2023-08-17 13:41 UTC, silabs-robin commented on tb/uvmt/uvmt_cv32e40x_tb.sv
> +  assign obi_instr_if.reqpar    = ~obi_instr_if.req;
These are the OBI asserts that fail if we don't connect these unused signals on the X.

The better solution would probably be to introduce a flag to the assertion set, to see if parity is supported or not.

![image](https://github.com/openhwgroup/cv32e40x-dv/assets/75431602/d1931461-5a06-4832-a83c-d31e00d8b09b)

2023-08-21 08:22 UTC, kristinedosvik commented on tb/uvmt/uvmt_cv32e40x_interrupt_assert.sv
> +    model_sleepmode === core_sleep_o
Aa, okei, interesting, thanks,

2023-08-21 08:25 UTC, kristinedosvik commented on tb/uvmt/uvmt_cv32e40x_tb.sv
> +  assign obi_instr_if.reqpar    = ~obi_instr_if.req;
I see. Thanks! Agree, a flag there sounds like a good idea! (If I remember it, I can fix it when I have some free time)

2023-08-21 08:32 UTC, silabs-krdosvik commented on tb/uvmt/uvmt_cv32e40x_tb.sv
> +  assign obi_instr_if.reqpar    = ~obi_instr_if.req;
I see. Thanks! Agree, a flag there sounds like a good idea! (If I remember it, I can fix it when I have some free time)

2023-08-21 08:33 UTC, silabs-krdosvik commented on tb/uvmt/uvmt_cv32e40x_interrupt_assert.sv
> +    model_sleepmode === core_sleep_o
Aa, okei, interesting, thanks,