Merge clic from s
openhwgroup/cv32e40x-dv pull request #30
Opened 2023-08-23 12:36 UTC by silabs-krdosvik

Merge clic updates from S to X.
Formal compiles
ci check: all green except clic test (which is ironic, but probably a test problem)

2023-08-23 13:38 UTC, silabs-mateilga requested changes
Looks good, but there are a few user-mode related parts that should be removed.

2023-08-23 13:38 UTC, silabs-mateilga commented on tb/uvmt/uvmt_cv32e40x_clic_interrupt_assert.sv
> +        (rvfi_mcause_fields.minhv && rvfi_mcause_fields.mpp != U_MODE) && rvfi_if.rvfi_pc_wdata == mepc_as_pointer_rdata;
The check for user mode could be removed, but as it will never be true it won't hurt to leave it in. Illegal behaviour would cause the assert to fail.

2023-08-23 13:38 UTC, silabs-mateilga commented on tb/uvmt/uvmt_cv32e40x_clic_interrupt_assert.sv
> +          intended_mode_u <= !rvfi_if.rvfi_trap.trap && (
As with my previous comment, there is quite a bit of user mode-related functionality here, but I don't think there will be any problems related to keeping it in. The logic would be simplified, but I'm not sure it's trivial to remove it, so I suggest we leave it in.

2023-08-23 13:38 UTC, silabs-mateilga commented on tb/uvmt/uvmt_cv32e40x_clic_interrupt_assert.sv
> +      or
As above, clean U-mode removal to plug a hole in the assert. Lines 2853 - 2855

2023-08-23 13:38 UTC, silabs-mateilga commented on tb/uvmt/uvmt_cv32e40x_clic_interrupt_assert.sv
> +        rvfi_if.rvfi_intr.intr && ((rvfi_mintstatus_fields.mil >= rvfi_mintthresh_fields.th) || intended_mode_u)
`|| intended_mode_u` should be removed from line 2912

2023-08-24 07:01 UTC, silabs-krdosvik commented on tb/uvmt/uvmt_cv32e40x_clic_interrupt_assert.sv
> +        (rvfi_mcause_fields.minhv && rvfi_mcause_fields.mpp != U_MODE) && rvfi_if.rvfi_pc_wdata == mepc_as_pointer_rdata;
Good catch, I think I will remove it.

2023-08-24 07:48 UTC, silabs-krdosvik commented on tb/uvmt/uvmt_cv32e40x_clic_interrupt_assert.sv
> +        (rvfi_mcause_fields.minhv && rvfi_mcause_fields.mpp != U_MODE) && rvfi_if.rvfi_pc_wdata == mepc_as_pointer_rdata;
RESOLVED? @silabs-mateilga

2023-08-24 07:49 UTC, silabs-krdosvik commented on tb/uvmt/uvmt_cv32e40x_clic_interrupt_assert.sv
> +          intended_mode_u <= !rvfi_if.rvfi_trap.trap && (
I removed it as it seemed straight forward.
RESOLVED? @silabs-mateilga

2023-08-24 07:49 UTC, silabs-krdosvik commented on tb/uvmt/uvmt_cv32e40x_clic_interrupt_assert.sv
> +        rvfi_if.rvfi_mode == U_MODE &&
RESOLVED? @silabs-mateilga

2023-08-24 07:49 UTC, silabs-krdosvik commented on tb/uvmt/uvmt_cv32e40x_clic_interrupt_assert.sv
> +      or
RESOLVED? @silabs-mateilga

2023-08-24 07:49 UTC, silabs-krdosvik commented on tb/uvmt/uvmt_cv32e40x_clic_interrupt_assert.sv
> +        rvfi_if.rvfi_intr.intr && ((rvfi_mintstatus_fields.mil >= rvfi_mintthresh_fields.th) || intended_mode_u)
RESOLVED? @silabs-mateilga

2023-08-24 08:14 UTC, silabs-mateilga commented on tb/uvmt/uvmt_cv32e40x_clic_interrupt_assert.sv
> +        (rvfi_mcause_fields.minhv && rvfi_mcause_fields.mpp != U_MODE) && rvfi_if.rvfi_pc_wdata == mepc_as_pointer_rdata;
yes

2023-08-24 08:14 UTC, silabs-mateilga commented on tb/uvmt/uvmt_cv32e40x_clic_interrupt_assert.sv
> +      or
yes

2023-08-24 08:15 UTC, silabs-mateilga commented on tb/uvmt/uvmt_cv32e40x_clic_interrupt_assert.sv
> +        rvfi_if.rvfi_intr.intr && ((rvfi_mintstatus_fields.mil >= rvfi_mintthresh_fields.th) || intended_mode_u)
yes

2023-08-24 08:15 UTC, silabs-mateilga approved these changes
All issues resolved, approving

2023-08-24 10:57 UTC, silabs-robin approved these changes
Approving based on:
Marton's approval.

--------

> all green except clic test (which is ironic

lol

2023-08-24 10:57 UTC, merged