atomic && remove xsecure features
openhwgroup/cv32e40x-dv pull request #39
Opened 2023-09-13 11:46 UTC by silabs-krdosvik

Added atomic
Removed xsecure features from support logic (as this gives warnings).

Should be merge at the same time as this: https://github.com/openhwgroup/core-v-verif/pull/2198
And after this: https://github.com/openhwgroup/cv32e40x/pull/947

ci check passes except the clic and debug_test2 (which seems to fail due to something else)
Formal compiles.

2023-09-13 12:38 UTC, silabs-robin requested changes
Blocking based on:
_"Should be merge [...] after this: https://github.com/openhwgroup/cv32e40x/pull/947"_.

2023-09-13 13:59 UTC, silabs-robin commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +      rvfi_if.rvfi_mem_atop[IS_ATOMIC_OPERATION]
Should the inverse be true too?

2023-09-13 13:59 UTC, silabs-robin commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +    c_atomic_lrw_exokay_ignore: cover property (
IIRC, we went for `cov_` as the standard prefix for cover properties?

2023-09-13 14:17 UTC, silabs-robin commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
Except, we want PRs to "main" to pass ci_check.
So that x/dev PR should include a hash update after this one is merged.

2023-09-13 14:38 UTC, silabs-robin commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +    c_atomic_lrw_exokay_ignore: cover property (
It's a mess. Guidelines doesn't say. We have a mix.

Disregard this comment.

2023-09-14 06:58 UTC, silabs-krdosvik commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
Okei, will update hash in another PR after this one then

2023-09-14 07:00 UTC, silabs-krdosvik commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
simulation warnings. Cant remember eexacly, but maybe something about the parity and integrity signals are not driven.

2023-09-14 07:04 UTC, silabs-krdosvik commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +  localparam IS_ATOMIC_OPERATION         = 5;
Aa, true. Do you have a suggestion for a better name. If not I will just remove the "IS"-part.

2023-09-14 07:08 UTC, silabs-krdosvik commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +        reservation_valid <= 1'b0;
That is true. That will be shown by the exokay signal in the assertions. This logic is used to make sure exokay is not set as if the reservation set is not valid or dont contain the correct address. So other devices interference will be covered by the exokay signal.

2023-09-14 07:10 UTC, silabs-krdosvik commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +      rvfi_if.rvfi_mem_atop[IS_ATOMIC_OPERATION]
Good point. Will add an assertion for it.

2023-09-14 07:44 UTC, silabs-robin commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
Oh ok. Nice to get that cleaned up.

2023-09-14 08:08 UTC, silabs-mateilga requested changes

2023-09-14 08:08 UTC, silabs-mateilga commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +    a_atomic_alignment_exceptions: assert property (
I think this assert would be tidier if it was split up, as there are parallell OR's in both antecedent and consequent.

2023-09-14 08:08 UTC, silabs-mateilga commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +    // TODO: Change assertion to check for equivalence:
Could we resolve this TODO before merging?

2023-09-14 08:08 UTC, silabs-mateilga commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +      || rvfi_if.rvfi_insn[31:27] == 5'b00011
I'd prefer these "magic numbers" to be localparams for readability.

2023-09-14 08:08 UTC, silabs-mateilga commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +      data_obi_if.atop[4:0] == 5'b00010
Same as above

2023-09-14 09:10 UTC, silabs-krdosvik commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +  localparam IS_ATOMIC_OPERATION         = 5;
Make sense, will use. ATOP_ATOMIC_POS.

2023-09-14 09:16 UTC, silabs-krdosvik commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +      (!(data_obi_if.req && data_obi_if.gnt) until_with data_obi_if.rvalid)
Good point. I will remove the data_obi_if.gnt signal form the consequent.

2023-09-14 09:21 UTC, silabs-krdosvik commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +      (!(data_obi_if.req && data_obi_if.gnt && (data_obi_if.atop[5] == 1)) until_with data_obi_if.rvalid)
Agreed!

2023-09-14 09:24 UTC, silabs-krdosvik commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +    // TODO: Change assertion to check for equivalence:
This is what was there from before, relating the A_EXT=ATOMIC and not A_EXT=ZALRSC, so since we are not interestead in this for now, and these assertions are not covered in a vplan, I have not taken the time to adjust or change them. I am not sure if we should. I think it would be more clean to state what we need to check in a vplan before making the assertions, to make sure the assertion set cover what is need to be covered.

2023-09-14 09:29 UTC, silabs-krdosvik commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +    a_atomic_alignment_exceptions: assert property (
Sound good.

2023-09-14 12:00 UTC, silabs-krdosvik commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +    // TODO: Change assertion to check for equivalence:
This is old and un-updated code which is not necessary for ZARLSC so I will just leave it.

2023-09-14 12:00 UTC, silabs-krdosvik commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +      data_obi_if.atop[4:0] == 5'b00010
This is old and un-updated code which is not necessary for ZARLSC so I will just leave it.

2023-09-14 12:29 UTC, silabs-mateilga commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +      support_if.asm_rvfi.instr == LR_W
This line is now meaningless, as it's assured in the antecedent.

2023-09-14 12:29 UTC, silabs-mateilga commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
>        support_if.asm_rvfi.instr == SC_W)
same as above

2023-09-14 12:41 UTC, silabs-krdosvik commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +    // TODO: Change assertion to check for equivalence:
removed as it check the decoder

2023-09-14 12:42 UTC, silabs-krdosvik commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +      data_obi_if.atop[4:0] == 5'b00010
Just added a TODO for it

2023-09-14 12:43 UTC, silabs-krdosvik commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +      support_if.asm_rvfi.instr == LR_W
true!

2023-09-27 08:25 UTC, silabs-robin commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +  localparam IS_ATOMIC_OPERATION         = 5;
Please drop a comment to notify when it is done.

2023-09-27 08:38 UTC, silabs-krdosvik commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +  localparam IS_ATOMIC_OPERATION         = 5;
I have committed the change IS_ATOMIC_OPERATION --> ATOP_ATOMIC_OPERATION_POS, if that is what you mean?

2023-09-27 08:40 UTC, silabs-krdosvik commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +      rvfi_if.rvfi_mem_atop[IS_ATOMIC_OPERATION]
Done

2023-09-27 08:50 UTC, silabs-mateilga approved these changes
All issues I've seen have been resolved, approving. I don't have the permissions required to resolve the conversations.

2023-09-27 09:18 UTC, silabs-robin commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +  localparam IS_ATOMIC_OPERATION         = 5;
The change looks good. Resolving.

2023-09-27 09:20 UTC, silabs-robin commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +      rvfi_if.rvfi_mem_atop[IS_ATOMIC_OPERATION]
Looks good. (Looks like `a_atomic_atop_5_zalrsc` is the one.) Resolving.

2023-09-27 09:24 UTC, silabs-robin approved these changes
Approving based on:
The atomics assertions are a nice addition, thanks.
The dependency PR has been merged. (Though, not sure about hash updates.)
All feedback has been resolved, and other reviewer has approved.
Test status ok.

2023-09-27 09:25 UTC, silabs-robin reviewed
The merge conflict has to be resolved before it is possible to merge.

2023-09-27 14:32 UTC, silabs-krdosvik commented on tb/assertions/uvmt_cv32e40x_atomic_assert.sv
> +  localparam IS_ATOMIC_OPERATION         = 5;
Agreed. I will go for the second option in the future.

2023-09-28 07:26 UTC, merged